// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Efficiency_of_Power_PlantML.Model
{
    public class ModelInput
    {
        [ColumnName("ID"), LoadColumn(0)]
        public float ID { get; set; }


        [ColumnName("Date"), LoadColumn(1)]
        public string Date { get; set; }


        [ColumnName("Water"), LoadColumn(2)]
        public float Water { get; set; }


        [ColumnName("Gas"), LoadColumn(3)]
        public float Gas { get; set; }


        [ColumnName("Power"), LoadColumn(4)]
        public float Power { get; set; }


    }
}
